[auth_call]
type = registration
transport = transport-tcp
outbound_auth = auth_call
server_uri = sip:sip.cpx2.ru
client_uri = sip:4983029903@sip.cpx2.ru
contact_user = 4983029903
retry_interval = 60
forbidden_retry_interval = 300
expiration = 300
line = yes
endpoint = auth_call

[auth_call]
type = auth
auth_type = userpass
username = 4983029903
password = BhAVNf81

[auth_call]
type = aor
max_contacts = 1
remove_existing = yes
contact = sip:sip.cpx2.ru:5060
qualify_frequency = 30

[auth_call]
type = endpoint
transport = transport-tcp
context = default
disallow = all
allow = alaw,ulaw
aors = auth_call
outbound_auth = auth_call
from_domain = sip.cpx2.ru
from_user = 4983029903
direct_media = no
rewrite_contact = yes
rtp_symmetric = yes
force_rport = yes
trust_id_inbound = yes
send_pai = yes
identify_by = ip,username

[auth_call]
type = identify
endpoint = auth_call
match = 185.8.127.215/32
